import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Cart from "@/components/Cart";
import { getDictionary } from "./dictionaries";
import { useRouter } from "next/router";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export async function generateStaticParams() {
    return [{ lang: 'en' }, { lang: 'ru' }];
}

export default async function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: { lang: string };
}) {
    const { lang } = params; 
    const translate = await getDictionary(lang); 

    
    

    return (
        <html lang={lang}>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="wrapper">
                    <Header translate={translate} lang={lang}/>
                    <main className="w-[1200px] max-1200:w-[900px] max-992:w-[700px] flex">
                        <Cart translate={translate}/>
                        {children}
                    </main>
                    <Footer translate={translate} />
                </div>
            </body>
        </html>
    );
}
